# Generated by Django 3.2 on 2023-09-01 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(default='none', max_length=60)),
                ('name', models.CharField(default='none', max_length=255)),
                ('phone_no', models.CharField(default='none', max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.CharField(choices=[('1', 'Customer'), ('2', 'Employee')], max_length=10)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(default='none', max_length=255)),
                ('user_code', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'EmailCode',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('nickname', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=6)),
            ],
            options={
                'db_table': 'Customer',
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='UserKeywords',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('beverage', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('dessert', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('various_menu', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('special_menu', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('large_store', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('background', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('talking', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('concentration', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('trendy_store', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('gift_packaging', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('price', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'UserKeywords',
            },
        ),
    ]
