# Generated by Django 4.2.1 on 2023-06-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sex',
            field=models.CharField(choices=[('Male', '1'), ('Female', '2')], max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Customer', '1'), ('Employee', '2')], max_length=10),
        ),
    ]
