# Generated by Django 4.2.1 on 2023-06-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customer_sex_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sex',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('1', 'Customer'), ('2', 'Employee')], max_length=10),
        ),
    ]
