# Generated by Django 4.2.1 on 2023-06-06 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('cafe_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('business_name', models.CharField(max_length=255)),
                ('cafe_name', models.CharField(max_length=255)),
                ('cafe_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('visitor_reviews', models.IntegerField()),
                ('blog_reviews', models.IntegerField()),
                ('cafe_phone_no', models.CharField(blank=True, max_length=20)),
                ('cafe_info', models.TextField(blank=True)),
                ('business_hours', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cafe_image', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'Cafe',
            },
        ),
        migrations.CreateModel(
            name='CafeKeywords',
            fields=[
                ('cafe', models.ForeignKey(db_column='cafe_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cafe.cafe')),
                ('beverage', models.FloatField()),
                ('dessert', models.FloatField()),
                ('various_menu', models.FloatField()),
                ('special_menu', models.FloatField()),
                ('large_store', models.FloatField()),
                ('background', models.FloatField()),
                ('talking', models.FloatField()),
                ('concentration', models.FloatField()),
                ('trendy_store', models.FloatField()),
                ('label', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')])),
                ('gift_packaging', models.BooleanField()),
                ('parking', models.BooleanField()),
                ('price', models.BooleanField(default=False)),
                ('common_keywords', models.FloatField()),
            ],
            options={
                'db_table': 'CafeKeywords',
            },
        ),
        migrations.CreateModel(
            name='VisitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spend', models.DecimalField(decimal_places=0, max_digits=10)),
                ('visit_date', models.DateTimeField()),
                ('cafe', models.ForeignKey(db_column='cafe_id', on_delete=django.db.models.deletion.CASCADE, to='cafe.cafe')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'VisitHistory',
            },
        ),
        migrations.CreateModel(
            name='CafeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('rating_date', models.DateTimeField()),
                ('cafe', models.ForeignKey(db_column='cafe_id', on_delete=django.db.models.deletion.CASCADE, to='cafe.cafe')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'CafeRating',
            },
        ),
    ]
