# Generated by Django 3.2 on 2023-12-24 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('cafe_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('cafe_name', models.CharField(max_length=255)),
                ('cafe_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('visitor_reviews', models.IntegerField()),
                ('blog_reviews', models.IntegerField()),
                ('cafe_phone_no', models.CharField(blank=True, max_length=20)),
                ('cafe_info', models.TextField(blank=True)),
                ('business_hours', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cafe_image', models.URLField(blank=True, max_length=1024)),
            ],
            options={
                'db_table': 'Cafe',
            },
        ),
        migrations.CreateModel(
            name='CafeKeyword',
            fields=[
                ('cafe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cafe.cafe')),
                ('dessert', models.FloatField()),
                ('various_menu', models.FloatField()),
                ('special_menu', models.FloatField()),
                ('large_store', models.FloatField()),
                ('background', models.FloatField()),
                ('talking', models.FloatField()),
                ('concentration', models.FloatField()),
                ('trendy_store', models.FloatField()),
                ('label', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')])),
                ('gift_packaging', models.BooleanField()),
                ('parking', models.BooleanField()),
                ('price', models.BooleanField(default=False)),
                ('beverage', models.FloatField()),
                ('clean_store', models.FloatField()),
                ('service', models.FloatField()),
            ],
            options={
                'db_table': 'CafeKeyword',
            },
        ),
        migrations.CreateModel(
            name='CafeKeywords',
            fields=[
                ('cafe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cafe.cafe')),
                ('beverage', models.FloatField()),
                ('dessert', models.FloatField()),
                ('various_menu', models.FloatField()),
                ('special_menu', models.FloatField()),
                ('large_store', models.FloatField()),
                ('background', models.FloatField()),
                ('talking', models.FloatField()),
                ('concentration', models.FloatField()),
                ('trendy_store', models.FloatField()),
                ('label', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')])),
                ('gift_packaging', models.BooleanField()),
                ('parking', models.BooleanField()),
                ('price', models.BooleanField(default=False)),
                ('common_keywords', models.FloatField()),
            ],
            options={
                'db_table': 'CafeKeywords',
            },
        ),
    ]
