# Generated by Django 3.2 on 2023-11-17 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeKeyword',
            fields=[
                ('cafe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cafe.cafe')),
                ('dessert', models.FloatField()),
                ('various_menu', models.FloatField()),
                ('special_menu', models.FloatField()),
                ('large_store', models.FloatField()),
                ('background', models.FloatField()),
                ('talking', models.FloatField()),
                ('concentration', models.FloatField()),
                ('trendy_store', models.FloatField()),
                ('label', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')])),
                ('gift_packaging', models.BooleanField()),
                ('parking', models.BooleanField()),
                ('price', models.BooleanField(default=False)),
                ('beverage', models.FloatField()),
                ('clean_store', models.FloatField()),
                ('service', models.FloatField()),
            ],
            options={
                'db_table': 'CafeKeyword',
            },
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='business_name',
        ),
    ]
