# Generated by Django 3.2 on 2023-11-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_auto_20231117_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='cafe_image',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
